Repository catho/quantum, pull requests merged in 2019-12, with the labels that each got.

#173 Fix/circular loader
  components/CircularLoader/CircularLoader.jsx
  components/CircularLoader/__snapshots__/CircularLoader.unit.test.jsx.snap
Labels: status:approved

#174 [Feat/socials]: create a social component
  .loki/reference/chrome_iphone7_Slider_default.png
  .loki/reference/chrome_iphone7_Slider_disabled.png
  .loki/reference/chrome_iphone7_Slider_from_to.png
  .loki/reference/chrome_iphone7_Slider_min_and_max.png
  .loki/reference/chrome_iphone7_Slider_min_max_formmater.png
  .loki/reference/chrome_iphone7_Socials_All_items.png
  .loki/reference/chrome_iphone7_Socials_All_items_24px.png
  .loki/reference/chrome_iphone7_Socials_all_items_24px.png
  .loki/reference/chrome_iphone7_Socials_all_items_without_box.png
  .loki/reference/chrome_iphone7_Socials_all_items_without_box_24px.png
  .loki/reference/chrome_iphone7_Socials_only_Facebook.png
  .loki/reference/chrome_iphone7_Socials_only_Twitter.png
  .loki/reference/chrome_iphone7_Socials_only_Youtube.png
  .loki/reference/chrome_laptop_Slider_default.png
  .loki/reference/chrome_laptop_Slider_disabled.png
  .loki/reference/chrome_laptop_Slider_from_to.png
  .loki/reference/chrome_laptop_Slider_min_and_max.png
  .loki/reference/chrome_laptop_Slider_min_max_formmater.png
  .loki/reference/chrome_laptop_Socials_All_items.png
  .loki/reference/chrome_laptop_Socials_All_items_24px.png
  .loki/reference/chrome_laptop_Socials_all_items_24px.png
  .loki/reference/chrome_laptop_Socials_all_items_without_box.png
  .loki/reference/chrome_laptop_Socials_all_items_without_box_24px.png
  .loki/reference/chrome_laptop_Socials_only_Facebook.png
  .loki/reference/chrome_laptop_Socials_only_Twitter.png
  .loki/reference/chrome_laptop_Socials_only_Youtube.png
  .storybook/regression-test/stories.js
  .storybook/stories.js
  components/Socials/Socials.jsx
  components/Socials/Socials.unit.test.jsx
  components/Socials/__snapshots__/Socials.unit.test.jsx.snap
  components/Socials/index.js
  components/Socials/sub-components/SocialFacebookIcon.jsx
  components/Socials/sub-components/SocialIcons.js
  components/Socials/sub-components/SocialTwitterIcon.jsx
  components/Socials/sub-components/SocialType.jsx
  components/Socials/sub-components/SocialType.unit.test.jsx
  components/Socials/sub-components/SocialYoutubeIcon.jsx
  components/Socials/sub-components/__snapshots__/SocialType.unit.test.jsx.snap
  components/index.js
  stories/Socials/Socials.regression-test.story.jsx
  stories/Socials/Socials.story.jsx
  stories/Socials/examples/SocialExampleAll.jsx
  stories/Socials/examples/SocialExampleChangingSize.jsx
  stories/Socials/examples/SocialExampleFacebook.jsx
  stories/Socials/examples/SocialExampleWithoutBox.jsx
  stories/Socials/examples/SocialExampleWithoutBoxChangingSize.jsx
  stories/Socials/examples/SocialExamples.js
Labels: status:approved

#175 fix(vulnerabilities): fix
  yarn.lock
Labels: status:approved

#177 feat(accordion): creates accordion with pending issues
  .loki/reference/chrome_iphone7_Accordion_Accordion.png
  .loki/reference/chrome_laptop_Accordion_Accordion.png
  .storybook/regression-test/stories.js
  .storybook/stories.js
  components/Accordion/Accordion.jsx
  components/Accordion/Accordion.unit.test.jsx
  components/Accordion/__snapshots__/Accordion.unit.test.jsx.snap
  components/Accordion/index.js
  components/Accordion/mock.jsx
  components/index.js
  package.json
  stories/Accordion/Accordion.regression-test.story.jsx
  stories/Accordion/Accordion.story.jsx
  stories/Accordion/examples.jsx
  yarn.lock
Labels: status:pending review

#176 (pagination) add "rel=nofollow" for SEO purposes
  .loki/reference/chrome_iphone7_Pagination_default.png
  .loki/reference/chrome_laptop_Pagination_default.png
  components/Pagination/Pagination.jsx
  components/Pagination/Pagination.unit.test.jsx
  components/Pagination/__snapshots__/Pagination.unit.test.jsx.snap
  components/Pagination/sub-components/Desktop.jsx
  components/Pagination/sub-components/Mobile.jsx
  stories/Pagination/Pagination.regression-test.story.jsx
  stories/Pagination/Pagination.story.jsx
Labels: question, status:approved
