Repository catho/quantum, pull requests merged in 2019-09, with the labels that each got.

#117 fix: Eslint critical warning
  yarn.lock
Labels: dependencies

#124 fix: Upgrade libs to remove vulnerabilities
  components/List/__snapshots__/List.unit.test.jsx.snap
  components/List/sub-components/__snapshots__/Content.unit.test.jsx.snap
  components/List/sub-components/__snapshots__/Header.unit.test.jsx.snap
  components/List/sub-components/__snapshots__/Item.unit.test.jsx.snap
  components/List/sub-components/__snapshots__/SubHeader.unit.test.jsx.snap
  components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap
  yarn.lock
Labels: dependencies

#123 fix: Semantic release upgrade
  components/List/__snapshots__/List.unit.test.jsx.snap
  components/List/sub-components/__snapshots__/Content.unit.test.jsx.snap
  components/List/sub-components/__snapshots__/Header.unit.test.jsx.snap
  components/List/sub-components/__snapshots__/Item.unit.test.jsx.snap
  components/List/sub-components/__snapshots__/SubHeader.unit.test.jsx.snap
  components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap
  yarn.lock
Labels: dependencies

#125 feat(circularLoader): Creates CircularLoader component
  .loki/reference/chrome_iphone7_CircularLoader_default.png
  .loki/reference/chrome_iphone7_CircularLoader_with_custom_size.png
  .loki/reference/chrome_iphone7_CircularLoader_with_large_size.png
  .loki/reference/chrome_iphone7_CircularLoader_with_medium_size.png
  .loki/reference/chrome_iphone7_CircularLoader_with_secondary_theme.png
  .loki/reference/chrome_iphone7_CircularLoader_with_xlarge_size.png
  .loki/reference/chrome_iphone7_CircularLoader_with_xxlarge_size.png
  .loki/reference/chrome_iphone7_CircularLoader_with_xxxlarge_size.png
  .loki/reference/chrome_laptop_CircularLoader_default.png
  .loki/reference/chrome_laptop_CircularLoader_with_custom_size.png
  .loki/reference/chrome_laptop_CircularLoader_with_large_size.png
  .loki/reference/chrome_laptop_CircularLoader_with_medium_size.png
  .loki/reference/chrome_laptop_CircularLoader_with_secondary_theme.png
  .loki/reference/chrome_laptop_CircularLoader_with_xlarge_size.png
  .loki/reference/chrome_laptop_CircularLoader_with_xxlarge_size.png
  .loki/reference/chrome_laptop_CircularLoader_with_xxxlarge_size.png
  .storybook/regression-test/stories.js
  .storybook/stories.js
  components/CircularLoader/CircularLoader.jsx
  components/CircularLoader/CircularLoader.unit.test.jsx
  components/CircularLoader/__snapshots__/CircularLoader.unit.test.jsx.snap
  components/CircularLoader/index.js
  components/index.js
  stories/CircularLoader/CircularLoader.regression-test.story.jsx
  stories/Loaders/Loaders.story.jsx
Labels: status:approved

#129 Feat/skeletons
  .loki/reference/chrome_iphone7_Skeleton_Button.png
  .loki/reference/chrome_iphone7_Skeleton_Tag.png
  .loki/reference/chrome_iphone7_Skeleton_circle.png
  .loki/reference/chrome_iphone7_Skeleton_rect_as_default.png
  .loki/reference/chrome_iphone7_Skeleton_text.png
  .loki/reference/chrome_laptop_Skeleton_Button.png
  .loki/reference/chrome_laptop_Skeleton_Tag.png
  .loki/reference/chrome_laptop_Skeleton_circle.png
  .loki/reference/chrome_laptop_Skeleton_rect_as_default.png
  .loki/reference/chrome_laptop_Skeleton_text.png
  .storybook/regression-test/stories.js
  components/Skeleton/Skeleton.jsx
  components/Skeleton/Skeleton.unit.test.jsx
  components/Skeleton/SkeletonTypes.jsx
  components/Skeleton/__snapshots__/Skeleton.unit.test.jsx.snap
  components/Skeleton/index.js
  components/Skeleton/sub-components/SkeletonBase.jsx
  components/Skeleton/sub-components/SkeletonButton.jsx
  components/Skeleton/sub-components/SkeletonCircle.jsx
  components/Skeleton/sub-components/SkeletonRect.jsx
  components/Skeleton/sub-components/SkeletonTag.jsx
  components/Skeleton/sub-components/SkeletonText.jsx
  components/Skeleton/sub-components/index.js
  components/index.js
  stories/Loaders/Examples/Skeleton.jsx
  stories/Loaders/Examples/index.js
  stories/Loaders/Loaders.story.jsx
  stories/Skeleton/Skeleton.regression-test.story.jsx
Labels: status:approved

#133 build(RegressionTest): Adds test to prepush
  package.json
  scripts/run-regression.sh
Labels: enhancement, status:approved

#137 docs: Pull request template
  docs/PULL_REQUEST_TEMPLATE.md
Labels: status:pending review

#136 fix(input): adds parameter to onchange function on input component
  components/Input/Input.jsx
Labels: status:approved

#138 feat(snackbar): adds examples to snackbar stories
  stories/SnackBar/SnackBar.story.jsx
  stories/SnackBar/examples/SnackBarExampleError.jsx
  stories/SnackBar/examples/SnackBarExamplePrimary.jsx
  stories/SnackBar/examples/SnackBarExampleSuccess.jsx
  stories/SnackBar/examples/index.js
Labels: status:approved

#139 fix(manager-head): removes console warning in storybook
  .storybook/manager-head.html
Labels: status:approved

#142 fix(progressbar): fix progressbar issue
  components/ProgressBar/ProgressBar.jsx
  shared/helpers.js
Labels: bug, status:approved, status:priority
