Repository catho/quantum, pull requests merged in 2019-10, with the labels that each got.

#143 Feat/regression tests on ci
  .travis.yml
  package.json
Labels: enhancement, status:approved

#145 Revert "Feat/regression tests on ci"
  .travis.yml
  package.json
Labels: status: to review

#146 Feat/regression tests on ci
  .travis.yml
  package.json
Labels: status: to review

#148 Revert "Feat/regression tests on ci"
  .travis.yml
  package.json
Labels: status: to review

#141 chore(pull-request-template): update the description of pull request template
  docs/PULL_REQUEST_TEMPLATE.md
Labels: status:approved

#150 fix(input): fix input divergences from style guide
  .loki/reference/chrome_iphone7_Dropdown_default.png
  .loki/reference/chrome_iphone7_Dropdown_disabled.png
  .loki/reference/chrome_iphone7_Dropdown_error.png
  .loki/reference/chrome_iphone7_Dropdown_required.png
  .loki/reference/chrome_iphone7_Input_disabled.png
  .loki/reference/chrome_iphone7_Input_error.png
  .loki/reference/chrome_iphone7_Input_search.png
  .loki/reference/chrome_iphone7_Input_with_default_value.png
  .loki/reference/chrome_iphone7_TextArea_disabled.png
  .loki/reference/chrome_iphone7_TextArea_helperText.png
  .loki/reference/chrome_iphone7_TextArea_label.png
  .loki/reference/chrome_iphone7_TextArea_placeholder.png
  .loki/reference/chrome_iphone7_TextArea_required.png
  .loki/reference/chrome_laptop_Dropdown_default.png
  .loki/reference/chrome_laptop_Dropdown_disabled.png
  .loki/reference/chrome_laptop_Dropdown_error.png
  .loki/reference/chrome_laptop_Dropdown_required.png
  .loki/reference/chrome_laptop_Input_disabled.png
  .loki/reference/chrome_laptop_Input_error.png
  .loki/reference/chrome_laptop_Input_search.png
  .loki/reference/chrome_laptop_Input_with_default_value.png
  .loki/reference/chrome_laptop_TextArea_disabled.png
  .loki/reference/chrome_laptop_TextArea_helperText.png
  .loki/reference/chrome_laptop_TextArea_label.png
  .loki/reference/chrome_laptop_TextArea_placeholder.png
  .loki/reference/chrome_laptop_TextArea_required.png
  components/Dropdown/__snapshots__/Dropdown.unit.test.jsx.snap
  components/Form/__snapshots__/Form.unit.test.jsx.snap
  components/Input/Input.jsx
  components/Input/Input.unit.test.jsx
  components/Input/__snapshots__/Input.mask.unit.test.jsx.snap
  components/Input/sub-components/InputErrorMessage.jsx
  components/Input/sub-components/InputLabel.jsx
  components/Input/sub-components/TextInput.jsx
  components/Input/sub-components/__snapshots__/TextInput.unit.test.jsx.snap
  components/TextArea/__snapshots__/TextArea.unit.test.jsx.snap
  stories/Input/Input.regression-test.story.jsx
Labels: status:approved

#151 Fix/qtm 66 text area
  .loki/reference/chrome_iphone7_TextArea_pre_valued.png
  .loki/reference/chrome_laptop_TextArea_pre_valued.png
  components/TextArea/TextArea.jsx
  components/TextArea/TextArea.unit.test.jsx
  components/TextArea/__snapshots__/TextArea.unit.test.jsx.snap
  stories/TextArea/TextArea.regression-test.story.jsx
Labels: status:approved

#152 [Refactor/modal] Alinhar componente Modal com o styleguide
  .loki/reference/chrome_iphone7_Modal_modal_with_button_actions.png
  .loki/reference/chrome_iphone7_Modal_simple_modal.png
  .loki/reference/chrome_iphone7_Modal_simple_modal_with_small_text_title.png
  .loki/reference/chrome_laptop_Modal_modal_with_button_actions.png
  .loki/reference/chrome_laptop_Modal_simple_modal.png
  .loki/reference/chrome_laptop_Modal_simple_modal_with_small_text_title.png
  .storybook/regression-test/stories.js
  components/Modal/Modal.jsx
  components/Modal/__snapshots__/Modal.unit.test.jsx.snap
  components/Modal/sub-components/Content.jsx
  components/Modal/sub-components/Header.jsx
  stories/Modal/Modal.regression-test.story.jsx
  stories/Modal/Modal.story.jsx
  stories/Modal/examples/ModalSmallTitleExample.jsx
Labels: help wanted, status:approved

#153 feat(pagination): changes pagination styles
  .loki/reference/chrome_iphone7_Pagination_basic.png
  .loki/reference/chrome_iphone7_Pagination_custom_next_prev_buttons.png
  .loki/reference/chrome_iphone7_Pagination_default.png
  .loki/reference/chrome_iphone7_Pagination_helperText.png
  .loki/reference/chrome_iphone7_Pagination_several_pages_and_active.png
  .loki/reference/chrome_laptop_Pagination_basic.png
  .loki/reference/chrome_laptop_Pagination_custom_next_prev_buttons.png
  .loki/reference/chrome_laptop_Pagination_default.png
  .loki/reference/chrome_laptop_Pagination_helperText.png
  .loki/reference/chrome_laptop_Pagination_several_pages_and_active.png
  components/Pagination/__snapshots__/Pagination.unit.test.jsx.snap
  components/Pagination/sub-components/ActionButton.jsx
  components/Pagination/sub-components/Mobile.jsx
  components/Pagination/sub-components/PageButton.jsx
  components/Pagination/sub-components/__snapshots__/ActionButton.unit.test.jsx.snap
  components/Pagination/sub-components/__snapshots__/PageButton.unit.test.jsx.snap
Labels: status:approved

#157 fix(tooltip): Fix Tooltip component position and padding. also adds r…
  .loki/reference/chrome_iphone7_Tooltip_bottom.png
  .loki/reference/chrome_iphone7_Tooltip_left.png
  .loki/reference/chrome_iphone7_Tooltip_right.png
  .loki/reference/chrome_iphone7_Tooltip_top.png
  .loki/reference/chrome_laptop_Tooltip_bottom.png
  .loki/reference/chrome_laptop_Tooltip_left.png
  .loki/reference/chrome_laptop_Tooltip_right.png
  .loki/reference/chrome_laptop_Tooltip_top.png
  .storybook/regression-test/stories.js
  components/Slider/__snapshots__/Slider.unit.test.jsx.snap
  components/Tooltip/Tooltip.jsx
  components/Tooltip/__snapshots__/Tooltip.unit.test.jsx.snap
  components/Tooltip/options.js
  stories/Tooltip/Tooltip.regression-test.story.jsx
  stories/Tooltip/Tooltip.story.jsx
  stories/Tooltip/examples/TooltipExampleBottom.jsx
  stories/Tooltip/examples/TooltipExampleLeft.jsx
  stories/Tooltip/examples/TooltipExampleRight.jsx
  stories/Tooltip/examples/TooltipExampleTop.jsx
  stories/Tooltip/examples/examples.jsx
Labels: status:approved

#160 Test/tooltip regression
  .loki/reference/chrome_iphone7_Tooltip_bottom.png
  .loki/reference/chrome_iphone7_Tooltip_left.png
  .loki/reference/chrome_iphone7_Tooltip_right.png
  .loki/reference/chrome_iphone7_Tooltip_top.png
  .loki/reference/chrome_laptop_Tooltip_bottom.png
  .loki/reference/chrome_laptop_Tooltip_left.png
  .loki/reference/chrome_laptop_Tooltip_right.png
  .loki/reference/chrome_laptop_Tooltip_top.png
Labels: status:pending review

#155 style(Checkbox): update checkboxes
  .loki/reference/chrome_iphone7_Checkbox_checked.png
  .loki/reference/chrome_iphone7_Checkbox_default.png
  .loki/reference/chrome_iphone7_Checkbox_disabled.png
  .loki/reference/chrome_iphone7_Checkbox_error.png
  .loki/reference/chrome_iphone7_Checkbox_label.png
  .loki/reference/chrome_iphone7_Checkbox_value.png
  .loki/reference/chrome_iphone7_Dropdown_error.png
  .loki/reference/chrome_iphone7_Input_error.png
  .loki/reference/chrome_iphone7_RadioGroup_error.png
  .loki/reference/chrome_iphone7_TextArea_helperText.png
  .loki/reference/chrome_laptop_Checkbox_checked.png
  .loki/reference/chrome_laptop_Checkbox_default.png
  .loki/reference/chrome_laptop_Checkbox_disabled.png
  .loki/reference/chrome_laptop_Checkbox_error.png
  .loki/reference/chrome_laptop_Checkbox_label.png
  .loki/reference/chrome_laptop_Checkbox_value.png
  .loki/reference/chrome_laptop_Dropdown_error.png
  .loki/reference/chrome_laptop_Input_error.png
  .loki/reference/chrome_laptop_RadioGroup_error.png
  .loki/reference/chrome_laptop_TextArea_helperText.png
  components/Checkbox/Checkbox.jsx
  components/Checkbox/CheckboxGroup.jsx
  components/Checkbox/__snapshots__/Checkbox.unit.test.jsx.snap
  components/Checkbox/__snapshots__/CheckboxGroup.unit.test.jsx.snap
  components/Dropdown/__snapshots__/Dropdown.unit.test.jsx.snap
  components/Input/__snapshots__/Input.mask.unit.test.jsx.snap
  components/Input/sub-components/InputErrorMessage.jsx
  components/RadioGroup/RadioGroup.jsx
  components/RadioGroup/__snapshots__/RadioGroup.unit.test.jsx.snap
  components/TextArea/__snapshots__/TextArea.unit.test.jsx.snap
  components/shared/ErrorMessage.jsx
Labels: status:approved

#162 fix/radio-button: update component with the style guide
  .loki/reference/chrome_iphone7_RadioGroup_default.png
  .loki/reference/chrome_iphone7_RadioGroup_disabled.png
  .loki/reference/chrome_iphone7_RadioGroup_error.png
  .loki/reference/chrome_laptop_RadioGroup_default.png
  .loki/reference/chrome_laptop_RadioGroup_disabled.png
  .loki/reference/chrome_laptop_RadioGroup_error.png
  components/RadioGroup/Radio.jsx
  components/RadioGroup/RadioButton.jsx
  components/RadioGroup/__snapshots__/Radio.unit.test.jsx.snap
  components/RadioGroup/__snapshots__/RadioButton.unit.test.jsx.snap
  components/RadioGroup/__snapshots__/RadioGroup.unit.test.jsx.snap
Labels: status:approved
