Repository catho/quantum, pull requests merged in 2020-05, with the labels that each got.

#228 fix(JAS-581): Adjust to enable input dropdown to recognize other props
  .loki/reference/chrome_iphone7_Card_AdvancedCard.png
  .loki/reference/chrome_laptop_Card_AdvancedCard.png
  components/Dropdown/Dropdown.jsx
  components/Dropdown/Dropdown.unit.test.jsx
Labels: status:approved

#227 feat(TabbedView): imeplements callback function on tab click
  components/TabbedView/TabbedView.jsx
  components/TabbedView/TabbedView.unit.test.jsx
  components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap
  stories/TabbedView/TabbedView.story.jsx
Labels: status:approved, status:suggestion

#230 fix(Tabbedview): update ts interface of component
  components/TabbedView/index.d.ts
Labels: status:approved

#231 feat(Pagination): Allow onClick event return in onClick handler function
  components/Pagination/Pagination.jsx
  components/Pagination/Pagination.unit.test.jsx
  stories/Pagination/Pagination.story.jsx
  stories/Pagination/examples/ControlledPagination.jsx
Labels: status:approved

#237 fix(Node): change node version
  .nvmrc
  .travis.yml
Labels: status:do not merge
