Repository catho/quantum, pull requests merged in 2020-02, with the labels that each got.

#184 fix(QTM-150): fixes the display grid fallback in Edge 15
  components/Grid/sub-components/Col.jsx
Labels: status: to review

#183 [DOCS] Updated README to reference the types package
  README.md
Labels: status:pending review

#185 fix: Fixes pagination window verification
  components/Pagination/Pagination.jsx
Labels: status:approved

#186 feat(Dropdown): Add property to ignore special chars
  components/Dropdown/Dropdown.jsx
  components/Dropdown/Dropdown.unit.test.jsx
  components/shared/index.js
  components/shared/normalizeChars.js
  components/shared/normalizeChars.unit.test.js
  stories/Dropdown/Dropdown.story.jsx
  stories/Dropdown/examples.jsx
Labels: status:approved

#187 feat(AUTH-153): [MD] add ts types
  components/Accordion/index.d.ts
  components/Alert/index.d.ts
  components/Badge/index.d.ts
  components/Breakpoints/index.d.ts
  components/Button/IconButton.d.ts
  components/Button/index.d.ts
  components/Card/Content.d.ts
  components/Card/Description.d.ts
  components/Card/Footer.d.ts
  components/Card/Header.d.ts
  components/Card/HeaderText.d.ts
  components/Card/Media.d.ts
  components/Card/Thumbnail.d.ts
  components/Card/Title.d.ts
  components/Card/index.d.ts
  components/Checkbox/index.d.ts
  components/CircularLoader/index.d.ts
  components/Colors/index.d.ts
  components/Dropdown/index.d.ts
  components/Form/index.d.ts
  components/GlobalStyle/index.d.ts
  components/Grid/index.d.ts
  components/Hamburguer/index.d.ts
  components/Icon/index.d.ts
  components/Input/index.d.ts
  components/Modal/index.d.ts
  components/Pagination/index.d.ts
  components/Popover/index.d.ts
  components/ProgressBar/index.d.ts
  components/RadioGroup/index.d.ts
  components/RangeSlider/index.d.ts
  components/Skeleton/index.d.ts
  components/SnackBar/index.d.ts
  components/Socials/index.d.ts
  components/TabbedView/index.d.ts
  components/Tag/index.d.ts
  components/TextArea/index.d.ts
  components/Toggle/index.d.ts
  components/Tooltip/index.d.ts
  components/index.d.ts
  package.json
Labels: status:approved

#188 docs(Readme): Updates readme
  .all-contributorsrc
  README.md
Labels: status: to review

#191 fix(Dropdown): Fixes autocomplete typing filter
  components/Dropdown/Dropdown.jsx
  components/Dropdown/__snapshots__/Dropdown.unit.test.jsx.snap
Labels: status:approved

#193 feat(normalize-char): Add new char in normalizeChars function
  components/shared/normalizeChars.js
  components/shared/normalizeChars.unit.test.js
Labels: status:approved

#192 AUTH-164: Issue #189
  components/Accordion/index.d.ts
  components/Alert/index.d.ts
  components/Button/index.d.ts
  components/Checkbox/index.d.ts
  components/GlobalStyle/index.d.ts
  components/Grid/index.d.ts
  components/Hamburger/index.d.ts
  components/Hamburguer/index.d.ts
  components/Icon/index.d.ts
  components/Input/index.d.ts
  components/Modal/index.d.ts
  components/Pagination/index.d.ts
  components/Popover/index.d.ts
  components/ProgressBar/index.d.ts
  components/RadioGroup/index.d.ts
  components/RangeSlider/index.d.ts
  components/Skeleton/index.d.ts
  components/SnackBar/index.d.ts
  components/Socials/index.d.ts
  components/TabbedView/index.d.ts
  components/Tag/index.d.ts
  components/TextArea/index.d.ts
  components/Toggle/index.d.ts
  components/Tooltip/index.d.ts
  components/index.d.ts
Labels: status:approved

#194 fix(Dropdown): adds name attribute on input hidden
  components/Dropdown/Dropdown.jsx
  components/Dropdown/Dropdown.unit.test.jsx
  components/Dropdown/__snapshots__/Dropdown.unit.test.jsx.snap
Labels: status: to review

#196 AUTH-165 Added SocialButton component
  .loki/reference/chrome_iphone7_SocialButtons_provider_facebook.png
  .loki/reference/chrome_iphone7_SocialButtons_provider_google.png
  .loki/reference/chrome_laptop_SocialButtons_provider_facebook.png
  .loki/reference/chrome_laptop_SocialButtons_provider_google.png
  components/SocialButton/SocialButton.jsx
  components/SocialButton/SocialButton.unit.test.jsx
  components/SocialButton/__snapshots__/SocialButton.unit.test.jsx.snap
  components/SocialButton/index.d.ts
  components/SocialButton/index.js
  components/SocialButton/sub-components/FacebookIcon.jsx
  components/SocialButton/sub-components/FacebookIcon.unit.test.jsx
  components/SocialButton/sub-components/GoogleIcon.jsx
  components/SocialButton/sub-components/GoogleIcon.unit.test.jsx
  components/SocialButton/sub-components/__snapshots__/FacebookIcon.unit.test.jsx.snap
  components/SocialButton/sub-components/__snapshots__/GoogleIcon.unit.test.jsx.snap
  stories/Button/Button.regression-test.story.jsx
  stories/Button/Button.story.jsx
Labels: status:approved
