Repository catho/quantum, pull requests merged in 2021-02, with the labels that each got.

#292 feat(Step/QTM-243): creates Stepper component
  .loki/reference/chrome_iphone7_Stepper_Stepper_with_total_2.png
  .loki/reference/chrome_iphone7_Stepper_Stepper_with_total_3.png
  .loki/reference/chrome_iphone7_Stepper_Stepper_with_total_4.png
  .loki/reference/chrome_iphone7_Stepper_Stepper_with_total_5.png
  .loki/reference/chrome_iphone7_Stepper_Stepper_with_total_6.png
  .loki/reference/chrome_laptop_Stepper_Stepper_with_total_2.png
  .loki/reference/chrome_laptop_Stepper_Stepper_with_total_3.png
  .loki/reference/chrome_laptop_Stepper_Stepper_with_total_4.png
  .loki/reference/chrome_laptop_Stepper_Stepper_with_total_5.png
  .loki/reference/chrome_laptop_Stepper_Stepper_with_total_6.png
  .storybook/regression-test/stories.js
  .storybook/stories.js
  components/Stepper/Stepper.jsx
  components/Stepper/Stepper.unit.test.jsx
  components/Stepper/__snapshots__/Stepper.unit.test.jsx.snap
  components/Stepper/helper.js
  components/Stepper/index.js
  components/Stepper/style.js
  components/index.js
  stories/Stepper/Stepper.regression-test.story.jsx
  stories/Stepper/Stepper.story.jsx
Labels: status:pending review

#293 fix(Stepper component): fixes min-width for desktop
  components/Stepper/__snapshots__/Stepper.unit.test.jsx.snap
  components/Stepper/style.js
Labels: status: to review

#295 [Fix]: Creating Stepper types
  components/Stepper/index.d.ts
  components/index.d.ts
Labels: status:reviewing
