Repository catho/quantum, pull requests merged in 2022-02, with the labels that each got.

#373 feat(icon): Includes watch-later icon
  components/Icon/Icon.jsx
  components/shared/icons.js
Labels: status:approved

#367 docs(AutoComplete):Hiding old autocomplete prop and adding new AutoComplete to form story
  stories/AutoComplete/AutoComplete.story.jsx
  stories/Dropdown/Dropdown.story.jsx
  stories/Dropdown/examples.jsx
Labels: status:approved, status: Sexta-bug

#374 Test(Qtm-326) - MIgrating Form, Grid and Hamburguer unit tests
  components/Form/Form.unit.test.jsx
  components/Form/__snapshots__/Form.unit.test.jsx.snap
  components/Grid/sub-components/Container.unit.test.jsx
  components/Grid/sub-components/Hide.unit.test.jsx
  components/Grid/sub-components/__snapshots__/Container.unit.test.jsx.snap
  components/Grid/sub-components/__snapshots__/Hide.unit.test.jsx.snap
  components/Hamburger/Hamburger.jsx
  components/Hamburger/Hamburger.unit.test.jsx
  components/Hamburger/__snapshots__/Hamburger.unit.test.jsx.snap
Labels: status:approved, status:pending review, status:suggestion

#375 test(QTM-327): Migrates unit tests to testing-library/react
  components/GlobalStyle/GlobalStyle.unit.test.jsx
  components/GlobalStyle/sub-components/Blockquote.unit.test.jsx
  components/GlobalStyle/sub-components/Subtitle.unit.test.jsx
  components/GlobalStyle/sub-components/Title.unit.test.jsx
  components/GlobalStyle/sub-components/Typography.ssr.unit.test.jsx
  components/GlobalStyle/sub-components/Typography.unit.test.jsx
  components/GlobalStyle/sub-components/__snapshots__/Blockquote.unit.test.jsx.snap
  components/GlobalStyle/sub-components/__snapshots__/Subtitle.unit.test.jsx.snap
  components/GlobalStyle/sub-components/__snapshots__/Title.unit.test.jsx.snap
  components/GlobalStyle/sub-components/__snapshots__/Typography.ssr.unit.test.jsx.snap
  components/GlobalStyle/sub-components/__snapshots__/Typography.unit.test.jsx.snap
Labels: question, status:approved

#365 feat(QTM-320): Creates breadcrumbs component
  .loki/reference/chrome_iphone7_Breadcrumbs_Default.png
  .loki/reference/chrome_laptop_Breadcrumbs_Default.png
  .storybook/stories.js
  components/Breadcrumbs/Breadcrumbs.jsx
  components/Breadcrumbs/Breadcrumbs.unit.test.jsx
  components/Breadcrumbs/__snapshots__/Breadcrumbs.unit.test.jsx.snap
  components/Breadcrumbs/exampleContents.js
  components/Breadcrumbs/index.d.ts
  components/Breadcrumbs/index.js
  components/index.d.ts
  components/index.js
  jest-config.js
  package.json
  stories/Breadcrumbs/Breadcrumbs.regression-test.story.jsx
  stories/Breadcrumbs/Breadcrumbs.story.jsx
  yarn.lock
Labels: status:approved

#369 fix(QTM-335): Fixing input bug with external value
  components/Input/Input.jsx
  components/Input/Input.unit.test.jsx
Labels: status:approved

#376 fix(UseMaxWidthMediaQuery): Implementing support to safari and adding mock to jest config
  components/shared/helpers.js
  components/shared/hooks/UseMaxWidthMediaQuery/useMaxWidthMediaQuery.jsx
  components/shared/hooks/UseMaxWidthMediaQuery/useMaxWidthMediaQuery.unit.test.jsx
  jest-config.js
  stories/Hooks/Examples/UseMaxWidthMediaQueryExample.jsx
Labels: status:approved, status:suggestion

#377 Test(Qtm-328) - Migrating Icon, Input and List unit tests + Link
  components/Icon/Icon.unit.test.jsx
  components/Icon/__snapshots__/Icon.unit.test.jsx.snap
  components/Input/Input.mask.unit.test.jsx
  components/Input/Input.unit.test.jsx
  components/Input/__snapshots__/Input.mask.unit.test.jsx.snap
  components/Input/sub-components/TextInput.unit.test.jsx
  components/Input/sub-components/__snapshots__/TextInput.unit.test.jsx.snap
  components/Link/Link.unit.test.jsx
  components/Link/__snapshots__/Link.unit.test.jsx.snap
  components/List/List.unit.test.jsx
  components/List/__snapshots__/List.unit.test.jsx.snap
  components/List/sub-components/Content.unit.test.jsx
  components/List/sub-components/Header.unit.test.jsx
  components/List/sub-components/Item.jsx
  components/List/sub-components/Item.unit.test.jsx
  components/List/sub-components/SubHeader.unit.test.jsx
  components/List/sub-components/__snapshots__/Content.unit.test.jsx.snap
  components/List/sub-components/__snapshots__/Header.unit.test.jsx.snap
  components/List/sub-components/__snapshots__/Item.unit.test.jsx.snap
  components/List/sub-components/__snapshots__/SubHeader.unit.test.jsx.snap
Labels: status:approved

#379 Tests(Qtm-330) - Migrating ProgressBar, Radiogroup and RangeSlider unit tests
  components/ProgressBar/ProgressBar.unit.test.jsx
  components/ProgressBar/__snapshots__/ProgressBar.unit.test.jsx.snap
  components/RadioGroup/RadioButton.unit.test.jsx
  components/RadioGroup/RadioGroup.unit.test.jsx
  components/RadioGroup/__snapshots__/RadioButton.unit.test.jsx.snap
  components/RadioGroup/__snapshots__/RadioGroup.unit.test.jsx.snap
  components/RangeSlider/RangeSlider.jsx
  components/RangeSlider/RangeSlider.unit.test.jsx
  components/RangeSlider/__snapshots__/RangeSlider.unit.test.jsx.snap
Labels: status:approved

#378 test(QTM-329): Migrates unit tests to testing-library/react
  components/Modal/Modal.jsx
  components/Modal/Modal.unit.test.jsx
  components/Modal/__snapshots__/Modal.unit.test.jsx.snap
  components/Pagination/Pagination.unit.test.jsx
  components/Pagination/__snapshots__/Pagination.unit.test.jsx.snap
  components/Pagination/sub-components/ActionButton.unit.test.jsx
  components/Pagination/sub-components/Dots.unit.test.jsx
  components/Pagination/sub-components/PageButton.unit.test.jsx
  components/Pagination/sub-components/__snapshots__/ActionButton.unit.test.jsx.snap
  components/Pagination/sub-components/__snapshots__/Dots.unit.test.jsx.snap
  components/Pagination/sub-components/__snapshots__/PageButton.unit.test.jsx.snap
  components/Popover/Popover.jsx
  components/Popover/Popover.unit.test.jsx
  components/Popover/__snapshots__/Popover.unit.test.jsx.snap
  components/Popover/sub-components/Content.jsx
  package.json
  yarn.lock
Labels: status:approved

#380 test(QTM-332): Migrates unit tests to testing/library
  components/SocialButton/SocialButton.jsx
  components/SocialButton/SocialButton.unit.test.jsx
  components/SocialButton/__snapshots__/SocialButton.unit.test.jsx.snap
  components/SocialButton/sub-components/FacebookIcon.unit.test.jsx
  components/SocialButton/sub-components/GoogleIcon.unit.test.jsx
  components/SocialButton/sub-components/__snapshots__/FacebookIcon.unit.test.jsx.snap
  components/SocialButton/sub-components/__snapshots__/GoogleIcon.unit.test.jsx.snap
  components/Socials/Socials.unit.test.jsx
  components/Socials/__snapshots__/Socials.unit.test.jsx.snap
  components/Socials/sub-components/SocialType.jsx
  components/Socials/sub-components/SocialType.unit.test.jsx
  components/Socials/sub-components/__snapshots__/SocialType.unit.test.jsx.snap
  components/Stepper/Stepper.unit.test.jsx
  components/Stepper/__snapshots__/Stepper.unit.test.jsx.snap
Labels: status:approved

#383 Tests(Qtm-333) - Migrating TabbedView, Tag and Textarea unit tests
  components/TabbedView/TabbedView.unit.test.jsx
  components/TabbedView/__snapshots__/TabbedView.unit.test.jsx.snap
  components/Tag/Tag.unit.test.jsx
  components/Tag/__snapshots__/Tag.unit.test.jsx.snap
  components/TextArea/TextArea.unit.test.jsx
  components/TextArea/__snapshots__/TextArea.unit.test.jsx.snap
Labels: status:approved

#382 test(QTM-334): Migrates tests to testing library
  components/Toggle/Toggle.unit.test.jsx
  components/Toggle/__snapshots__/Toggle.unit.test.jsx.snap
  components/Tooltip/Tooltip.jsx
  components/Tooltip/Tooltip.unit.test.jsx
  components/Tooltip/__snapshots__/Tooltip.unit.test.jsx.snap
  components/shared/hooks/UseMaxWidthMediaQuery/useMaxWidthMediaQuery.unit.test.jsx
Labels: status:approved

#384 feat(QTM-337): Adds trending up Icon
  components/Icon/Icon.jsx
  components/shared/icons.js
Labels: status:approved

#387 fix(Social Button): rollback on a change due to quantum ui auto example error
  components/SocialButton/SocialButton.jsx
Labels: status:approved

#385 Feat(QTM-336) - Adding new email validation
  components/Form/Form.unit.test.jsx
  components/Form/__snapshots__/Form.unit.test.jsx.snap
  components/Form/index.d.ts
  components/Form/validations.js
Labels: status:approved, status:suggestion
