Repository catho/quantum, pull requests merged in 2022-01, with the labels that each got.

#359 chore(storybook): Updates storybook to version 6.4.9
  package.json
  yarn.lock
Labels: dependencies, status:approved

#360 fix(icon): Includes person_circle icon on TS definitions
  components/Icon/index.d.ts
Labels: status:approved

#357 chore(scripts): Sets component generator
  CONTRIBUTING.MD
  package.json
  scripts/create-component.js
  scripts/templates/component-story.js
  scripts/templates/component.js
Labels: status:approved

#358 Feat(QTM-295) - Implement clean AutoComplete
  .loki/reference/chrome_iphone7_AutoComplete_Default.png
  .loki/reference/chrome_iphone7_AutoComplete_With_Dark.png
  .loki/reference/chrome_iphone7_AutoComplete_With_Error.png
  .loki/reference/chrome_iphone7_AutoComplete_With_Helper_Text.png
  .loki/reference/chrome_laptop_AutoComplete_Default.png
  .loki/reference/chrome_laptop_AutoComplete_With_Dark.png
  .loki/reference/chrome_laptop_AutoComplete_With_Error.png
  .loki/reference/chrome_laptop_AutoComplete_With_Helper_Text.png
  .storybook/stories.js
  components/AutoComplete/AutoComplete.jsx
  components/AutoComplete/AutoComplete.unit.test.jsx
  components/AutoComplete/SubComponents/UseKeyPress.jsx
  components/AutoComplete/__snapshots__/AutoComplete.unit.test.jsx.snap
  components/AutoComplete/index.d.ts
  components/AutoComplete/index.js
  components/index.js
  stories/AutoComplete/AutoComplete.regression-test.story.jsx
  stories/AutoComplete/AutoComplete.story.jsx
Labels: status: to review

#364 Test(Qtm-322) Test migration - Enzyme to text-library: Accordion, Alert and Avatar
  components/Accordion/Accordion.jsx
  components/Accordion/Accordion.unit.test.jsx
  components/Accordion/__snapshots__/Accordion.unit.test.jsx.snap
  components/Accordion/mock.jsx
  components/Alert/Alert.unit.test.jsx
  components/Alert/__snapshots__/Alert.unit.test.jsx.snap
  components/Avatar/Avatar.unit.test.jsx
  components/Avatar/__snapshots__/Avatar.unit.test.jsx.snap
  package.json
  yarn.lock
Labels: question, status:pending review

#361 Feat(QTM-311) Implementing Link Component
  .loki/reference/chrome_iphone7_Link_Dark.png
  .loki/reference/chrome_iphone7_Link_Dark_Without_Underline.png
  .loki/reference/chrome_iphone7_Link_Default.png
  .loki/reference/chrome_iphone7_Link_Default_Without_Underline.png
  .loki/reference/chrome_laptop_Link_Dark.png
  .loki/reference/chrome_laptop_Link_Dark_Without_Underline.png
  .loki/reference/chrome_laptop_Link_Default.png
  .loki/reference/chrome_laptop_Link_Default_Without_Underline.png
  .storybook/stories.js
  components/Link/Link.jsx
  components/Link/Link.unit.test.jsx
  components/Link/__snapshots__/Link.unit.test.jsx.snap
  components/Link/index.d.ts
  components/Link/index.js
  components/index.js
  stories/Link/Link.regression-test.story.jsx
  stories/Link/Link.story.jsx
  stories/Link/style.js
Labels: status:pending review

#363 fix(QTM-321): Adjusts on ts props of all components
  .eslintrc.json
  components/Accordion/index.d.ts
  components/Alert/index.d.ts
  components/Avatar/index.d.ts
  components/Badge/index.d.ts
  components/Button/IconButton.d.ts
  components/Button/index.d.ts
  components/Card/Media.d.ts
  components/Carousel/index.d.ts
  components/ChargeBar/index.d.ts
  components/Checkbox/index.d.ts
  components/CircularLoader/index.d.ts
  components/Dialog/index.d.ts
  components/Dropdown/index.d.ts
  components/Grid/index.d.ts
  components/Icon/index.d.ts
  components/Input/index.d.ts
  components/List/index.d.ts
  components/Modal/index.d.ts
  components/ProgressBar/index.d.ts
  components/RadioGroup/index.d.ts
  components/RangeSlider/index.d.ts
  components/SegmentedControl/index.d.ts
  components/Skeleton/index.d.ts
  components/Skeleton/sub-components/SkeletonButton.jsx
  components/Skeleton/sub-components/SkeletonTag.jsx
  components/SnackBar/index.d.ts
  components/Socials/index.d.ts
  components/Stepper/index.d.ts
  components/TabbedView/index.d.ts
  components/Tag/index.d.ts
  components/TextArea/index.d.ts
  components/Toggle/index.d.ts
  components/Tooltip/index.d.ts
Labels: status:approved

#366 chore(storybook): Updates and moves storybook to devDependeces
  package.json
  yarn.lock
Labels: dependencies, status:approved, status: Sexta-bug

#362 Feat(Qtm-208) - Creating hook to check window size
  .storybook/stories.js
  components/shared/hooks/UseMaxWidthMediaQuery/Example.jsx
  components/shared/hooks/UseMaxWidthMediaQuery/index.js
  components/shared/hooks/UseMaxWidthMediaQuery/useMaxWidthMediaQuery.jsx
  components/shared/hooks/UseMaxWidthMediaQuery/useMaxWidthMediaQuery.unit.test.jsx
  components/shared/hooks/index.js
  stories/Hooks/Examples/UseMaxWidthMediaQueryExample.jsx
  stories/Hooks/Hooks.story.jsx
Labels: status:approved

#368 Tests(Qtm-323)Migrating Badge, Button,Card and AutoComplete Unit tests
  components/AutoComplete/AutoComplete.unit.test.jsx
  components/AutoComplete/__snapshots__/AutoComplete.unit.test.jsx.snap
  components/Badge/Badge.unit.test.jsx
  components/Badge/__snapshots__/Badge.unit.test.jsx.snap
  components/Button/Button.unit.test.jsx
  components/Button/__snapshots__/Button.unit.test.jsx.snap
  components/Card/Card.unit.test.jsx
  components/Card/__snapshots__/Card.unit.test.jsx.snap
  jest-config.js
  package.json
  yarn.lock
Labels: status:approved
