Repository catho/quantum, pull requests merged in 2022-04, with the labels that each got.

#393 fix(AutoComplete): Fixing function that filters the suggetion with user typed value
  components/AutoComplete/AutoComplete.jsx
  components/index.d.ts
  stories/AutoComplete/AutoComplete.story.jsx
Labels: status:approved

#395 Fix(QTM-345) Alert: Corrige callback onClose e atualiza TS
  components/Alert/Alert.jsx
  components/Alert/index.d.ts
Labels: status:approved, status:suggestion

#396 feat(Icon): adds wallet icon
  components/Icon/Icon.jsx
  components/Icon/index.d.ts
  components/shared/icons.js
Labels: status: to review

#394 Feat(TextArea AutoResize) - Adding autoResize function to textArea
  .loki/reference/chrome_iphone7_TextArea_Auto_Resize.png
  .loki/reference/chrome_iphone7_TextArea_Auto_Resize_With_Custom_Config.png
  .loki/reference/chrome_laptop_TextArea_Auto_Resize.png
  .loki/reference/chrome_laptop_TextArea_Auto_Resize_With_Custom_Config.png
  components/TextArea/TextArea.jsx
  components/TextArea/TextArea.unit.test.jsx
  components/TextArea/__snapshots__/TextArea.unit.test.jsx.snap
  components/TextArea/index.d.ts
  stories/TextArea/TextArea.regression-test.story.jsx
Labels: status:approved

#397 fix(Stepper): corrige resolução do componente em 1024+
  components/Stepper/__snapshots__/Stepper.unit.test.jsx.snap
  components/Stepper/style.js
Labels: status:approved

#398 fix(TextArea): fixes the current update state
  components/TextArea/TextArea.jsx
  components/TextArea/TextArea.unit.test.jsx
Labels: status:approved
